### ISSUE TITLE
3.26.3-scylla is failing in patch 

### ISSUE THREAD

**Issue by fruch** [scylladb/python-driver-matrix#65]
3.26.3-scylla was released yesterday

And it's failing the patch

```
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/main.py", line 23, in main
    result = Run(python_driver_git=arguments.python_driver_git,
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 173, in run
    if self._checkout_branch() and self._apply_patch_files() and self._install_python_requirements():
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 108, in _apply_patch_files
    self._run_command_in_shell(f"git apply --check {file_path}")
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 98, in _run_command_in_shell
    assert status_code == 0, stderr
AssertionError: (None, b'/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\nerror: patch failed: tests/integration/__init__.py:366\nerror: tests/integration/__init__.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_authentication_misconfiguration.py:38\nerror: tests/integration/standard/test_authentication_misconfiguration.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_client_warnings.py:27\nerror: tests/integration/standard/test_client_warnings.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_cluster.py:290\nerror: tests/integration/standard/test_cluster.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_custom_payload.py:43\nerror: tests/integration/standard/test_custom_payload.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_metadata.py:474\nerror: tests/integration/standard/test_metadata.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_query.py:957\nerror: tests/integration/standard/test_query.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_shard_aware.py:188\nerror: tests/integration/standard/test_shard_aware.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_types.py:731\nerror: tests/integration/standard/test_types.py: patch does not apply\n')
```

**Comment by fruch** [comment]
@k0machi we have one more patch to tix
