### ISSUE TITLE
3.26.5-scylla fails to apply

### ISSUE THREAD

**Issue by k0machi** [scylladb/python-driver-matrix#78]
Need to add support for new driver version as current patch is currently failing:
```
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/main.py", line 23, in main
    result = Run(python_driver_git=arguments.python_driver_git,
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 173, in run
    if self._checkout_branch() and self._apply_patch_files() and self._install_python_requirements():
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 108, in _apply_patch_files
    self._run_command_in_shell(f"git apply --check {file_path}")
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 98, in _run_command_in_shell
    assert status_code == 0, stderr
AssertionError: (None, b'/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\nerror: patch failed: tests/integration/__init__.py:372\nerror: tests/integration/__init__.py: patch does not apply\n')
```

**Comment by dkropachev** [comment]
Fixed
